# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule UnstructuredPipelineAPI.Model.HttpValidationError do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :detail
  ]

  @type t :: %__MODULE__{
    :detail => [UnstructuredPipelineAPI.Model.ValidationError1.t] | nil
  }

  alias UnstructuredPipelineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:detail, :list, UnstructuredPipelineAPI.Model.ValidationError1)
  end
end

