# NOTE: This file is auto generated by OpenAPI Generator 7.3.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule UnstructuredPipelineAPI.Model.ValidationError do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :loc,
    :msg,
    :type
  ]

  @type t :: %__MODULE__{
    :loc => [UnstructuredPipelineAPI.Model.ValidationError1LocInner.t],
    :msg => String.t,
    :type => String.t
  }

  alias UnstructuredPipelineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:loc, :list, UnstructuredPipelineAPI.Model.ValidationError1LocInner)
  end
end

